#!/bin/sh

vol_perc=$(pamixer --get-volume)
vol_mute=$(pamixer --get-mute)

if [[ $vol_mute == 'true' ]]
then
	echo '婢'
elif [[ $vol_perc -lt 10 ]]
then
	echo '奄'
elif [[ $vol_perc -lt 25 ]]
then
	echo '奔'
else
	echo '墳'
fi
